<a href="https://colab.research.google.com/github/Legendkiller9855/python-development-journey/blob/main/learning_python_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!")

Hello World!


used to add(join) two strings together.give space seprately if required

In [ ]:
print("Hello"+"World")

helloworldkrishan gupta


used to write multiline string

In [ ]:
print("Hello\nHello")

Hello
Hello


simply to get an input value.

In [ ]:
print("hello "+input("what is your name?")+"!")

what is your name?krishan
hellokrishan!


In [ ]:
print(input("what"))

whatk
k


In [ ]:
print("hello  "+input("what is your name?")+"!")

what is your name?kh
hello  kh!


to input a data and print its value


In [ ]:
name = input("what is your name?")
print(name)

what is your name?Krishan
Krishan


In [ ]:
name =("hello")
print(len(name))

5


To print a particular index of a string(This method is known as subscripting)

In [ ]:
print("Hello"[1])

e


To join two strings

In [ ]:
print("hello"+"123")

hello123


to add two numbers

In [ ]:
print(2345+7865)

10210


In [ ]:
print(True)#boolean data type
print(False)#boolean data type
print(4.5566)#float data type

True
False
4.5566


to know about the data type of a given value or expression

In [ ]:
print(type(123444))
print(type("Hello"))
print(type(True))
print(type(4.5566))

<class 'int'>
<class 'str'>
<class 'bool'>
<class 'float'>


To convert a data type into another data type

In [ ]:
print(int("12345"))
print(str("hello"))
print(float(90900))
print(bool(True))

12345
hello
90900.0
True


In [ ]:
name = input("What is your name?")#we are converting the length to a string type data integer as
print("the length of your name is: " + str(len(name)))#we can add two similar data types only

What is your name?Krishan
the length of your name is: 7


Mathematical Operations

In [ ]:
print("what is your age: " + str(123455))
print(8*7)#used for multiplication
print(77+77)#used for addition
print(77-77)#used for subtraction
print(67/6)#used for division(gives output as a float data type)
print(67//6)#used for division(gives output as a integer data type)
print(67&5)#used for finding remainder
print(8**2)#used for giving a powered value

what is your age: 123455
56
154
0
11.166666666666666
11
1
64


Priority Level of Mathematical Operations : BODMAS

B Bracket

O Of or Powered Value

D Division

M Multiplication

A Addition

S Subtraction

In [ ]:
print(3*3-3+3/3)

7.0


In [ ]:
print(round(15/8))#used to round off the value(rounding off is according to the nearest integer value from the actual decimal value)
print(round(119/33,2))#used to round off the value upto two decimal places.

2
3.61


In [ ]:
#f string is used to add a expression in a string
score = 0
height = 1.8
isWinning = True
print(f"your score is {score},your height is {height},your winning is {isWinning}")

your score is 0,your height is 1.8,your winning is True


In [ ]:
print("Roller Coaster Ride")
height = int(input(("what is your height?")))
if height>120:
  print("you can ride the roller coaster")
else:
  print("you can't ride the roller coaster")

Roller Coaster Ride
what is your height?12
you can't ride the roller coaster


Comparison Operators

Greater than >

Smaller than <

Is Equal to ==

Greater than or equal to >=

Smaller than or equal to <=

Not Equal to !=

Modulo Operator

% gives us the value of remainder

In [ ]:
number = int(input("what is your number: "))
problem =int(number%2)
if problem==0:
  print("even number")
else :
  print("odd number")

what is your number: 7
odd number


In [ ]:
print("Roller Coaster Ride")
height = int(input(("what is your height?")))
if height>120:
  print("you can ride the roller coaster")
  age = int(input("what is your age?"))
  if age<18:
    print("fare price is: 8$")
  elif age==18:
    print("fare price is: 10$")
  else:
    print("fare price is: 12$")
else:
  print("you can't ride the roller coaster")

Roller Coaster Ride
what is your height?34566
you can ride the roller coaster
what is your age?23
fare price is: 12$


if elif else is used in the situation when we don't want to check all the conditions

whereas in case of if if if all the statements are checked.

In [ ]:
print("Roller Coaster Ride")
height = int(input(("what is your height?")))
bill = int(0)  # Initialize bill as an integer
if height > 120:
  print("you can ride the roller coaster")
  age = int(input("what is your age?"))
  if age < 18:
    bill = 8  # Assign integer values to bill
  elif age == 18:
    bill = 10
  else:
    bill = 12
  do_you_want_photos = input("If you want photos type yes else no")

  if do_you_want_photos == "yes":
    bill += 3
    print(f"Your final bill is: ${bill}")

  else :
    bill += 0
    print(f"Your final bill is: ${bill}")

else:
  print("you can't ride the roller coaster")

Roller Coaster Ride
what is your height?8889
you can ride the roller coaster
what is your age?88
If you want photos type yes else noy
Your final bill is: $12


In [ ]:
print("Pizza Order App")
pizza_type = input("Veg or Non-Veg Pizza?") # Convert input to lowercase for easier comparison

bill = 0 # Initialize bill

if pizza_type == "veg":
  size_of_pizza = input(f"Small:4$ , Medium:6$ , Large:8$")
  if size_of_pizza == "small":
    bill = 4
  elif size_of_pizza == "medium":
    bill = 6
  else: # Assuming large is the only other option
    bill = 8
  extra_topping_cost = 3 # Cost for veg extra topping

else: # Assuming non-veg is the only other option
  size_of_pizza = input(f"Small:6$ , Medium:8$ , Large:10$").lower()
  if size_of_pizza == "small":
    bill = 6
  elif size_of_pizza == "medium":
    bill = 8
  else: # Assuming large is the only other option
    bill = 10
  extra_topping_cost = 5 # Cost for non-veg extra topping

extra_topping = input("if extra topping needed type yes else no: ")
if extra_topping == "yes":
  bill += extra_topping_cost

print(f"Your final bill is ${bill}")

Pizza Order App
Veg or Non-Veg Pizza?veg
Small:4$ , Medium:6$ , Large:8$large
if extra topping needed type yes else noyes
Your final bill is $11


Logical Operators:

and gives output true if both conditions are true

or gives output true even if one of the condition is true

In [ ]:
#Loop is the method performing a task again and again until we get our desired output.
fruits = ["apple","banana","cherry"]
for fruit in fruits:#will take fruit as a variable in list fruits and print all
  print(fruit)#the fruits individually and terminate until all the indexes are indexed in the list.
  print(fruit + " pie ")
  print(fruits)#this line will also run multiple times no matter the result will come same as the loop is running several times.

print(fruits)

apple
apple pie 
['apple', 'banana', 'cherry']
banana
banana pie 
['apple', 'banana', 'cherry']
cherry
cherry pie 
['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry']


In [ ]:
student_scores = [120,233,45,45,56,6,7,654]
total_score = sum(student_scores)
print(total_score)

1166


In [ ]:
student_score = [120,233,45,45,56,7,6,654]
total_score = 0
for score in student_score: # Use a different variable name for the loop
  total_score += score # Add the individual score to the total
print(total_score)

1166


In [ ]:
student_score = [120,233,45,45,56,7,6,654]
print(max(student_score))#used for finding max value in a list

654


In [ ]:
student_score = [120,233,45,45,56,7,6,654]
max_score = int(max(student_score))
print(max_score)
for value in student_score:
  if value>=max_score:
    print("Greatest number found")



654
Greatest number found


**Range function in loop is used to repeat a task several times in a desired range**

for number in range(a,b):

print(number)

In [ ]:
for number in range(1,11):#range includes a but not b i.e.1 to 10 will be printed
  print(number)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for number in range(1,11,2):#1,11 are the range and 2 means that after picking the first number pick the second number which is on 2nd position from
  print(number)#the first number
#matlab agar 2 likha hai toh ek ek chodh ke lena hai
total = 0
for number in range(1,101):
  print(number)
  total += number
print(total)

1
3
5
7
9
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
5050


**FOR LOOP is used to perform a task again and again until the result is achieved or it has reached the range of performing task.**

**SYNTAX : for name in range(0,4):  4 is not included**
             
             OR

**SYNTAX : for fruit in fruits:**             

**WHILE LOOP is used to perform a task again and again until the condition becomes false**

**SYNTAX : while condition:**
       

In [ ]:
print("HANGMAN")

word_list = ["python", "hangman", "challenge", "developer", "function", "variable",
             "keyboard", "condition", "iteration", "syntax", "string", "integer",
             "loop", "boolean", "exception", "dictionary", "module", "parameter",
             "argument", "recursion"]

import random
chosen_word = random.choice(word_list).lower()
print(chosen_word)  # You might want to remove this in actual gameplay

# Create initial placeholder for display
placeholder = ""
length_of_word = len(chosen_word)
for letter in range(length_of_word):
    placeholder += "_ "
print(placeholder)
print(f"The word has {length_of_word} letters")

# Initialize the display list with underscores
display = ["_"] * length_of_word

# Game variables
lives = 6
guessed_letters = []

game_over = False

# Main game loop
while not game_over:
    guess = input("Guess a letter: ").lower()

    if guess in guessed_letters:
        print(f"You've already guessed '{guess}'. Try again.")
        continue
    guessed_letters.append(guess)

    # Check guessed letter and update display
    correct_guess = False
    for index in range(length_of_word):
        if chosen_word[index] == guess:
            display[index] = guess
            correct_guess = True

    if not correct_guess:
        lives -= 1
        print(f"Wrong guess! Lives left: {lives}")
        if lives == 0:
            print("You lost! The word was:", chosen_word)
            game_over = True

    # Print current display
    print(" ".join(display))

    # Check if the player has won
    if "_" not in display:
        print("Congratulations! You guessed the word!")
        game_over = True


HANGMAN
string
_ _ _ _ _ _ 
The word has 6 letters
Guess a letter: l
Wrong guess! Lives left: 5
_ _ _ _ _ _
Guess a letter: s
s _ _ _ _ _
Guess a letter: t
s t _ _ _ _
Guess a letter: r
s t r _ _ _
Guess a letter: i
s t r i _ _
Guess a letter: n
s t r i n _
Guess a letter: g
s t r i n g
Congratulations! You guessed the word!


In [ ]:
def my_function():
  print("HELLO")
  print("BYE")
  a = 4
  print(a)
my_function()

HELLO
BYE
4


USING FUNCTION WITH OUR OWN INPUT.

In Python,a function with input(also called a parameter or argument) lets you pass data into a function so it can perform a task using that data.

It helps to input data using strings.

#Example:
def greet(name="Guest"):

  print("Hello",name)
  
greet("Riya")  #Output will be Hello Riya

greet()      #OUtput will be Error as no argument is given

              Instead use

def greet(name = "guest") as it will give output hello guest even if we call function as greet()  as the computer will be having a pre-defined parameter or argument.

In [ ]:
def my_function(name):
  print(f"My name is {name}")
  print(f"{name}")

my_function("Krishan")

My name is Krishan
Krishan


In [ ]:
def my_function(name ="Krishan",location = "Moga"):
  print(f"My name is {name}")
  print(f"I am from {location}")

#my_function("anand","ludhiana")
my_function(location="Ludhiana",name="anand")#used to specify

My name is anand
I am from Ludhiana


In [ ]:
def my_function(name ="Krishan",location = "Moga",age="20"):
  print(f"My name is {name}")
  print(f"I am from {location}")
  print(f"My age is {age}")

#my_function("anand","ludhiana")
my_function(location="Ludhiana",name="anand",age="21")

My name is anand
I am from Ludhiana
My age is 21


**A Dictionary in python is a collection of key-value pairs.**

**Dictionary is mutable i.e. it can be changed after creation**

**SYNTAX : dict = { key1:value1,key2,value2}



In [ ]:
dictionary = {
  "key1":"value1",
  "key2":"value2"
}
print(dictionary)#Used to print the whole dictionary
print(dictionary["key1"])#Used to print the value of a particular key.
dictionary["key3"] = "value3"#Used to add a new key and value in a dictionary.
print(dictionary)

empty_dictionary = {}#Used to create an empty dictionary
print(empty_dictionary)

dictionary = {}#Will set the dictionart to an empty dictionary as dictionary is mutable.
print(dictionary)

hello = {
    "key1":"value1",
    "key2":"value2",
    "key3":"value3",
}
hello["key1"]="value4"#Used to change the value of a key existing in a dictionary.
print(hello)



{'key1': 'value1', 'key2': 'value2'}
value1
{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
{}
{}
{'key1': 'value4', 'key2': 'value2', 'key3': 'value3'}


In [ ]:
#LOOP in a dictionary.
dictionary = {
    "bug" : "hello",
    "worm":"bye",
    "function":"value",
}

for thing in dictionary:
  print(thing)#Used to print the keys in a dictionary.
  print(dictionary[thing])#Used to print values in a dictionary.

bug
hello
worm
bye
function
value


In [ ]:
student_scores = {
    'Harry': 88,
    'Ron': 78,
    'Hermione': 95,
    'Draco': 75,
    'Neville': 60
}

student_grades = {}
for student in student_scores:
    score = student_scores[student]
    if score>=90:
        student_grades[student] = "A"
    elif score<=90 and score>=70:
        student_grades[student] = "A"
    else:
      student_grades[student]="FAIL"

print(student_grades)

In [ ]:
capitals = {
    "India":"Delhi",
    "USA":"Washington DC",
    "France":"Paris",
}
print(capitals)

city_travelled={
    "India":["Delhi","Goa","Moga"],#List can also be the value of a key in a dictionary.
    "USA":["Washington DC","New York"],
    "France":["Paris","Marseille"],
}
print(city_travelled["India"][1])#Used to print a particular value of list in a given dictionary using index value.

city_travelled["nested_list"] = ["A","B","C",["D","E"]] # Corrected syntax for adding a new key-value pair
print(city_travelled["nested_list"][3][0])

{'India': 'Delhi', 'USA': 'Washington DC', 'France': 'Paris'}
Goa
D


In [ ]:
travel_log = {
    "France":{
        "cities_visited":["Paris","Lille","Dijon"],
        "total_visits":12,
    },
    "Germany":{
        "cities_visited":["Berlin","Hamburg","Stuttgart"],
        "total_visits":5,
    },
}
print(travel_log["France"]["cities_visited"][1])
print(travel_log["France"]["total_visits"])

Lille
12


In [ ]:
def format_name(f_name = "First Name",l_name = "Last Name"):
  print(f_name.title())
  print(l_name.title())
  name = f_name + " " + l_name
  print(name)
format_name(l_name = "Gupta",f_name = "Krishan")

Krishan
Gupta
Krishan Gupta


Functions with OUTPUT:

SYNTAX :

In [ ]:
def my_function():
  f_name = "Krishan "
  l_name = "Gupta"
  name = f_name + l_name
  return name

my_function()

'KrishanGupta'

In [ ]:
def function_1(text):
  return text + text

def function_2(text):
  return text.title()

output = function_1("krishan")
print(output)

result = function_2(output)
print(result)
#OR
aim = function_2(function_1("krishan"))
print(aim)

krishankrishan
Krishankrishan
Krishankrishan


return keyword tells us that the function is over.We can have multiple return keywords in a function.

In [ ]:
def function(f_name="first",l_name="last"):
  formated_first_name = f_name.title()
  formated_last_name = l_name.title()
  return f"{formated_first_name} {formated_last_name}"
  print(function(l_name="gupta",f_name="krishan")) #Will not be executed as return keyword has marked the ending of the function.
function()

'First Last'

In [ ]:
def function(f_name="first",l_name="last"):
  if f_name == "" or l_name == "": #If this condition is satisfied it will return null value
    return
  formated_first_name = f_name.title()
  formated_last_name = l_name.title()
  return f"{formated_first_name} {formated_last_name}"

print(function(input("What is your name?"),input("What is your last name?")))

What is your name?
What is your last name?
None


In [ ]:
def is_leap_year(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False
is_leap_year(2000)

True

*Doctstring is a special kind of string used to document a module,class,method,or function.It helps others understand what the code is supposed to do.

SYNTAX : """""""(comment after the first line of function)

In [ ]:
def my_function(n1,n2):
  return n1+n2
my_favourite_operation = my_function#Used to store a function in another variable.To store simply remove the ()as brackets will trigger the function.
print(my_favourite_operation(2,3))#Used to run the variable which consists the function. i.e. the function will be triggered automatically


5


In [ ]:
def function(n1, n2):
  operations = {
      "+": n1 + n2,
      "-": n1 - n2,
      "*": n1 * n2,
      "/": n1 / n2,
  }
  return operations

result = function(n1=2, n2=4)
print(result["+"])

6


In [ ]:
def subtract(n1,n2):
  return n1-n2

def add(n1,n2):
  return n1+n2

def multiply(n1,n2):
  return n1*n2

def divide(n1,n2):
  return n1/n2

operations = {
    "-":subtract,
    "+":add,
    "*":multiply,
    "/":divide,
}
print(operations["*"](n1=4,n2=5))

20


In [ ]:
def subtract(n1,n2):
  return n1-n2

def add(n1,n2):
  return n1+n2

def multiply(n1,n2):
  return n1*n2

def divide(n1,n2):
  return n1/n2

operations = {
    "-":subtract,
    "+":add,
    "*":multiply,
    "/":divide,
}

def calculator():
  should_continue = True
  first_number =float(input("What's your first number?"))
  answer = 0

  while should_continue:
    operations_available = "*\n-\n+\n/"
    print(operations_available)
    operand_selected = input("What's the operator selected?")
    second_number=float(input("What's your next number?"))
    answer = operations[operand_selected](n1=first_number,n2=second_number)
    print(answer)
    print("If you want to continue the calculation type y , if you want to reset the calculator type n")
    wanna_continue =input("Want to continue the operations from the result or from the beginning?")
    if wanna_continue == "y":
      first_number = answer

    else:
      should_continue = False
  print(f"Your final solution is {answer}")

calculator()

In [ ]:
import random

def deal_card():
  """Returns a random card from the deck."""
  cards = [11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10]
  card = random.choice(cards)
  return card

def calculate_score(cards):
  """Take a list of cards and return the score calculated from the cards"""
  if sum(cards) == 21 and len(cards) == 2:
    return 0
  if 11 in cards and sum(cards) > 21:
    cards.remove(11)
    cards.append(1)
  return sum(cards)

def compare(user_score, computer_score):
  if user_score > 21 and computer_score > 21:
    return "You went over. You lose "
  if user_score == computer_score:
    return "Draw "
  elif computer_score == 0:
    return "Lose, opponent has Blackjack "
  elif user_score == 0:
    return "Win with a Blackjack "
  elif user_score > 21:
    return "You went over. You lose "
  elif computer_score > 21:
    return "Opponent went over. You win "
  elif user_score > computer_score:
    return "You win "
  else:
    return "You lose "

def play_game():
  user_cards = []
  computer_cards = []
  is_game_over = False

  for _ in range(2):
    user_cards.append(deal_card())
    computer_cards.append(deal_card())

  while not is_game_over:
    user_score = calculate_score(user_cards)
    computer_score = calculate_score(computer_cards)
    print(f"   Your cards: {user_cards}, current score: {user_score}")
    print(f"   Computer's first card: {computer_cards[0]}")

    if user_score == 0 or computer_score == 0 or user_score > 21:
      is_game_over = True
    else:
      user_should_deal = input("Type 'y' to get another card, type 'n' to pass: ")
      if user_should_deal == "y":
        user_cards.append(deal_card())
      else:
        is_game_over = True

  while computer_score != 0 and computer_score < 17:
    computer_cards.append(deal_card())
    computer_score = calculate_score(computer_cards)

  print(f"   Your final hand: {user_cards}, final score: {user_score}")
  print(f"   Computer's final hand: {computer_cards}, final score: {computer_score}")
  print(compare(user_score, computer_score))

while input("Do you want to play a game of Blackjack? Type 'y' or 'n': ") == "y":
  play_game()

Do you want to play a game of Blackjack? Type 'y' or 'n': y
   Your cards: [10, 2], current score: 12
   Computer's first card: 5
Type 'y' to get another card, type 'n' to pass: y
   Your cards: [10, 2, 8], current score: 20
   Computer's first card: 5
Type 'y' to get another card, type 'n' to pass: n
   Your final hand: [10, 2, 8], final score: 20
   Computer's final hand: [5, 10, 9], final score: 24
Opponent went over. You win 😁
Do you want to play a game of Blackjack? Type 'y' or 'n': n


***If we create a variable in if , while or for loop it is accesible by the whole code wherever if we create a variable in function it s only accesible by the function . Thus, this is the whole concept of local and global space.**

***Local space are the variables which are defined inside a function and is accessible only inside the function.**

***Global space are the variables defined outside all functions and classes and are accesible from anywhere in the script.**

In [ ]:
def is_prime(num):
    if num == 2:
        return True
    if num == 1:
        return False

    # Loop through all the numbers between 2 and the number
    for i in range(2, num):
        # Check if the number (num) can be divided by the potential prime number
        if num % i == 0:
            return False

    # this return is outside the for loop which will only run once the loop finishes and none of the numbers are divisible. Therefore it is prime.
    return True

In [ ]:
def is_prime(num):
    if num == 1:
        return False
    if num == 2:
        return True
    for i in range(2 , num):
        if num % i == 0:
            print("It's not a prime number.")
            return False
    print("It's a prime number.")
    return True

is_prime(75)
#Else statement should not be inside the for loop as it will check for the first number only and print the
#result that whether the given number is prime or not

It's not a prime number.


False

By writing global variable, we have made the variable accesible by the function.
global variable must be written inside the function itself.


In [ ]:
enemies = "Skeleton"
print(f"Enemies outside function: {enemies}")
def function():
  global enemies #BY writing this line we can access variables outside the function too.
  enemies = "Zombie"
  print(f"Enemies inside function: {enemies}")
function()


Enemies outside function: Skeleton
Enemies inside function: Zombie


In [ ]:
import random
dice_images = [1,2,3,4,5,6]
dice_num = random.randint(0,5)#We have taken 0 to 5 as while using the print function we are putting dice_num as index value and in
print(dice_images[dice_num])#list dice_images only index value from 0 to 5 is available.

3


In [ ]:
eligible_age = 18
try:
  age = int(input("How old are you?"))
except ValueError: #It will avoid such error and execute the statement we have used
  print("You have typed in a invalid number.Please try again with a numerical value such as 15.")
  age = int(input("How old are you?"))
if age>=18:
  print("You are eligible for driving license.")
else:
  print("You are not eligible for driving license.")
  print(f"You can drive at age {eligible_age} or older than {eligible_age}")

How old are you?12
You are not eligible for driving license.
You can drive at age 18 or older than 18


*= is used to put a value equal to a variable*

*whereas*

*== is used to check whether the given equation is equal to the given value or not.It's output is True or False*

In [ ]:
print("Hello World")
def function():
  print("Hello Krishan ")
  print("How are you?")
function()

Hello World
Hello Krishan 
How are you?


In [ ]:
class Student:#Creation of class
  name = "Krishan"#All students are named krishan but we will learn how to change it
s1 = Student()#Creation of Object
print(s1.name) #Will print the name which is krishan

Krishan


In [ ]:
class Car:
  model = 2005
  brand = "Mercedes"
  color = "Blue"
s1 =Car()
print(s1.color)
print(s1.brand)
print(s1.model)

Blue
Mercedes
2005


**PANDAS LIBRARY**

In [ ]:
import pandas as pd  #Will import pandas (python library)
df = pd.read_csv("https://storage.googleapis.com/kagglesdsdata/datasets/2844100/4904103/data.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250811%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250811T180021Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=b2a84269163d37e9d058087f19badec9455b6b71415ff5385d377f011aeb21abec3b10e9d08b8e1ad7b7793602fc751411a1eebbda72bdb8a11f0992075bb9b92cb4de2c0dd61d281b9ce1ddcbf81fbc78fb8249d5f2990ff6e5ed001f070d3f0f8332d95f546688328b3729f373993137343c7391ed44b7339be19f1e3d9ffbfbcdf6ca9ad54f1713569d5957bf8bdfa566dff7fcfd8c34c7169ecc64737c41c28f7b9d35f29e34396d0ec30764629bb86b653efe5ff9f539eca36a0871b7aa21b046fadb3693aa67c0d601c3eaf2f3d89602744bbe726a5d2bddeb6ae1211e6929a5309c96b13d2a8dcd0f754f8fc4b92040d3cfced1dfe640b4148a50a483")
#Will read the file
"""
df = pd.read_csv #For csv type of file
df = pd.read_excel #For excel type of file
df = pd.read_json #For json type of file
"""
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [ ]:
import pandas as pd

data = {
    "Name":["ram","Varun","Krishan"],
    "Age":[12,13,20],
    "City":["Nagpur","Chennai","Delhi"]
}
df = pd.DataFrame(data) #Used to create a dataframe of the given data
print(df)

df.to_csv("output.csv") #Will convert the file into csv form and save as output.csv
#df.to_csv("output.csv", index=False) #Used to remove the index 0 1 2 etc.which have popped up by itself.
#df.to_excel("output.xlsx")#For converting the file into excel file and save as output.xlsx
#df.to_json("output.json")#For Saving the file as json type and save as output.json


      Name  Age     City
0      ram   12   Nagpur
1    Varun   13  Chennai
2  Krishan   20    Delhi


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'col1': [1, 2, 3], 'col2': ['a', 'b', 'c']}
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('my_data.csv', index=False)

print("DataFrame saved to my_data.csv")

DataFrame saved to my_data.csv


In [ ]:
import pandas as pd
df = pd.read_csv("https://storage.googleapis.com/kagglesdsdata/datasets/2844100/4904103/data.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250812%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250812T053756Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2fac0104fd7d74e0a5797ced1cad8d7deeaa35957cb8ea095335b2483357edcbbb63937319c3b2030446e9e277aff707e8e792275d52453ce7797e80848fac61d88caa010baf64c05846d87c3d2dfde93c303af66549eaee6f13b52bff6290d823ae4d826a4bc684a1cf889477a74b7cd07ffabff5f4c3e46fbfec0372af0a56cfbce3647a59b95e0d1832ad7c171867328575d15fe7cc362568155bc82661b7c58307a7c27ad7aeef9df25931ebb78308659ab55742e836f390ef922133b6e557310f6d3acdf4fa6658cdd8fcd146d829c488e0b02f74e625d1b467cfb7019f934fec7ad5ee5a908eb6c71675e57adc8fbdc61fa2af0e69a13ddbf2381e7272")

print(df)

print("Show first 10 rows of the dataset")
print(df.head(10)) #Used to show starting rows of a dataset

print("Show last 10 rows of the dataset")
print(df.tail(10)) #Used to show ending rows of a dataset


    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [ ]:
import pandas as pd
data = {'col1': [1, 2, 3], 'col2': ['a', 'b', 'c']}
df = pd.DataFrame(data)


print(df.info) #Used to know the info of the datset i.e. It tells us about the number of rows and columns the particular dataset has
#It also tells us about the null  value it contains if any. Overall it gives us an overview of the whole dataset.

<bound method DataFrame.info of    col1 col2
0     1    a
1     2    b
2     3    c>


In [ ]:
import pandas as pd

data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
print("Sample Dataset")
print(df.to_string(index = False)) #Used to print the DataFrame with no index
print("Descriptive Staisticts")
print(df.describe()) #Used to find the statistics of the dataframe
#i.e. It tells us the count(number of non null values ), mean of each column , standard deviation of each column , tell the minimum(or least) value of each cloumn ,
#25 % mens that it will arrange the value in a ascending order and take average of firsr 25% to tell us that the given 25%value lie in this area,
#50% will tell the same but for range 25% to 50%
#75% will tell the same but for range 50% to 75%
#Highest will tell about the highes value in each column

Sample Dataset
   Name  Age  Salary  Performance Score
Krishan   21   30000                 99
 Kartik   23   20000                 98
Rakshit   32   12000                  9
  Anish   34   23000                 98
  Ayush   55   23500                 97
  Manan   43   12000                 97
 Akshat   45   23400                 98
 Shivam   34   18000                 90
Descriptive Staisticts
             Age        Salary  Performance Score
count   8.000000      8.000000           8.000000
mean   35.875000  20237.500000          85.750000
std    11.394704   6145.367012          31.139089
min    21.000000  12000.000000           9.000000
25%    29.750000  16500.000000          95.250000
50%    34.000000  21500.000000          97.500000
75%    43.500000  23425.000000          98.000000
max    55.000000  30000.000000          99.000000


In [ ]:
import pandas as pd

data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
print(df)
print(f'Shape : {df.shape}') #Will tell shape of the dataframe/dataset . output will be number of rows to number of cloumns
print(f'Column Names: {df.columns}') #Will tell the name of all columns it has

      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   23   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
Shape : (8, 4)
Column Names: Index(['Name', 'Age', 'Salary', 'Performance Score'], dtype='object')


In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
columns = df["Salary"] #To select a particular or single cloumn in a dataset.
print(columns)  #or directly we can do print(df["Salary"])
subset = df[["Age","Performance Score"]] # Use a list to select multiple columns
print(subset)
print("To filter a specific row in a cloumn with a single condition. ")
filtered_rows = df[df["Salary"] > 15000] #Condition is to filter rows in age column with salary more than 50,000.
#It will give whole data related to the rows with salary k=lesss than 50,000.That is there age,name,performance score etc.
print(filtered_rows)
print("To filter rows with more than one condition.")
filtered_salary  = df[(df["Salary"] > 12000) & (df["Salary"] < 30000)]
print(filtered_salary)
print("\nTo find person with less than age 25 and with good salary")
filtered_age  = df[(df["Salary"] > 12000) & (df["Salary"] < 20000) & (df["Age"] > 25)]
print(filtered_age)
print("\n To get any of the one condition to get true among the two conditions given.")
filtered_or  = df[(df["Salary"] < 28000) | (df["Performance Score"] < 95)]
print(filtered_or)
#By using & in two conditions both the condition must be fufilled to get the desired result.(& = and)
#By using | in two conditions either of the two conditions must be true to get the desired result.(| = or)

0    30000
1    20000
2    12000
3    23000
4    23500
5    12000
6    23400
7    18000
Name: Salary, dtype: int64
   Age  Performance Score
0   21                 99
1   23                 98
2   32                  9
3   34                 98
4   55                 97
5   43                 97
6   45                 98
7   34                 90
To filter a specific row in a cloumn with a single condition. 
      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   23   20000                 98
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
To filter rows with more than one condition.
     Name  Age  Salary  Performance Score
1  Kartik   23   20000                 98
3   Anish   34   23000                 98
4   Ayush   55   23500                 97
6  Akshat   45   23400                 98
7  Shivam   34   18000          

**Advance Pandas**

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
print(df)
df["Bonus"] = df["Salary"] * 0.1 # To add a new column in a given dataset.
print(df)
df.insert(2,"Employee ID",[11,12,13,14,15,16,17,18]) #To add  a new column in a dataset but with desired location.
#SYNTAX : df.insert(location where the column is needed to be add , Name of new column , Data of the new column )
print(df)

      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   23   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
      Name  Age  Salary  Performance Score   Bonus
0  Krishan   21   30000                 99  3000.0
1   Kartik   23   20000                 98  2000.0
2  Rakshit   32   12000                  9  1200.0
3    Anish   34   23000                 98  2300.0
4    Ayush   55   23500                 97  2350.0
5    Manan   43   12000                 97  1200.0
6   Akshat   45   23400                 98  2340.0
7   Shivam   34   18000                 90  1800.0
      Name  Age  Employee ID  Salary  Performance Score   Bonus
0  Krishan   21           11   30000                 99  3000.0
1   Kartik   23           

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
print(df)
df.loc[0,"Salary"] = 50000 #Used to update a value of a given row in a desired column.
#SYNTAX : df.loc[index of the row whose value is gonna upgrade, Column name whole value is being gonna upgrade] = new_value
print(df)


#To change the value of an entire column.
#SYNTAX : df["Column name "] = df["Column name "] * Condition
df["Salary"] = df["Salary"] * 1.12 # Changed "Salary " to "Salary"
print(df)

      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   23   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
      Name  Age  Salary  Performance Score
0  Krishan   21   50000                 99
1   Kartik   23   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
      Name  Age   Salary  Performance Score
0  Krishan   21  56000.0                 99
1   Kartik   23  22400.0                 98
2  Rakshit   32  13440.0                  9
3    Anish   34  25760.0                 98
4    A

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam"],
    "Age":[21,23,32,34,55,43,45,34],
    "Salary":[30000,20000,12000,23000,23500,12000,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90]
}
df = pd.DataFrame(data)
print(df)
df.drop(columns = ["Performance Score"],inplace = True)  #To remove a particular column in a given dataset
#By writing inplace is true we will update the original dataset else the system will give us a new dataset itself.
df.drop(columns = ["Performance Score","Age"],inplace = True) #To remove multiple columns from a single dataset.
print(df)

      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   23   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   23400                 98
7   Shivam   34   18000                 90
      Name  Age  Salary
0  Krishan   21   30000
1   Kartik   23   20000
2  Rakshit   32   12000
3    Anish   34   23000
4    Ayush   55   23500
5    Manan   43   12000
6   Akshat   45   23400
7   Shivam   34   18000


**Handling missing data in pandas**

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shivam",None],
    "Age":[21,23,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,None]
}
df = pd.DataFrame(data)
print(df)
print(df.isnull()) #Tell us whether the dataframe contains a null value or not.
#If the result is True it means it contains a null value else it contains some type of value.\

print(df.isnull().sum()) #Tells us the total number of null values and also the column in which it consists.

      Name  Age  Salary  Performance Score
0  Krishan   21   30000               99.0
1   Kartik   23   20000               98.0
2  Rakshit   32   12000                9.0
3    Anish   34   23000               98.0
4    Ayush   55   23500               97.0
5    Manan   43   12000               97.0
6   Akshat   45   33333               98.0
7   Shivam   34   23400               90.0
8     None   23   18000                NaN
    Name    Age  Salary  Performance Score
0  False  False   False              False
1  False  False   False              False
2  False  False   False              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7  False  False   False              False
8   True  False   False               True
Name                 1
Age                  0
Salary               0
Performance Score    1
dtype: int64


In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat",None,"Shivam"],
    "Age":[21,23,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,None]
}
df = pd.DataFrame(data)
print(df)
print(df.isnull()) #Tell us whether the dataframe contains a null value or not.
#If the result is True it means it contains a null value else it contains some type of value.\

print(df.isnull().sum()) #Tells us the total number of null values and also the column in which it consists.

df.dropna(inplace = True) #df.dropna is used to remove the empty or null values form the dataset.
#If we write df.dropna(axis = 0) , axis 0 means it will remove null value only from the rows and the axis = 1 means it will remove the null values from columns.
# inplace = True ,  is written to change or update the original dataset instead of creation of a new dataset.
print(df)


      Name  Age  Salary  Performance Score
0  Krishan   21   30000               99.0
1   Kartik   23   20000               98.0
2  Rakshit   32   12000                9.0
3    Anish   34   23000               98.0
4    Ayush   55   23500               97.0
5    Manan   43   12000               97.0
6   Akshat   45   33333               98.0
7     None   34   23400               90.0
8   Shivam   23   18000                NaN
    Name    Age  Salary  Performance Score
0  False  False   False              False
1  False  False   False              False
2  False  False   False              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7   True  False   False              False
8  False  False   False               True
Name                 1
Age                  0
Salary               0
Performance Score    1
dtype: int64
      Name  Age  Salary  Performanc

# **###CHEAT CODE FOR PANDAS###**

# **#For reading a file we use :**

df = pd.read_csv #For csv type of file

df = pd.read_excel #For excel type of file

df = pd.read_json #For json type of file

# **#To create a dataset from a raw data , WE use :**

df = pd.DataFrame(data) #Used to create a dataframe of the given data

# **#To Download a file with our own choice of name and file type**

df.to_csv("output.csv", index=False) #Used to remove the index 0 1 2 etc.which have popped up by itself.


df.to_excel("output.xlsx")#For converting the file into excel file and save as output.xlsx


df.to_json("output.json")#For Saving the file as json type and save as output.json

# **#To select our own choice of consecutive lines in a datset.(Either from top or Bottom)**

print(df.head(10)) #Used to show starting rows of a dataset.

print(df.tail(10)) #Used to show ending rows of a dataset.

# **#To know charactersticts about the dataset we are working on**


print(df.info) #Used to know the info of the datset i.e. It tells us about the number of rows and columns the particular dataset has
It also tells us about the null  value it contains if any. Overall it gives us an overview of the whole dataset.


print(df.describe()) #Used to find the statistics of the dataframe
i.e. It tells us the count(number of non null values ), mean of each column , standard deviation of each column , tell the minimum(or least) value of each cloumn ,
25 % mens that it will arrange the value in a ascending order and take average of firsr 25% to tell us that the given 25%value lie in this area,
50% will tell the same but for range 25% to 50%
75% will tell the same but for range 50% to 75%
Highest will tell about the highes value in each column

print(f'Shape : {df.shape}') #Will tell shape of the dataframe/dataset . output will be number of rows to number of cloumns
print(f'Column Names: {df.columns}') #Will tell the name of all columns it has

# **#General Queries or features of the pandas**

print(df.to_string(index = False)) #Used to print the DataFrame with no index

filtered_rows = df[df["Salary"] > 15000] #Condition is to filter rows in age column with salary more than 50,000.
It will give whole data related to the rows with salary k=lesss than 50,000.That is there age,name,performance score etc.


**print("\nTo find person with less than age 25 and with good salary")
filtered_age  = df[(df["Salary"] > 12000) & (df["Salary"] < 20000) & (df["Age"] > 25)]
print(filtered_age)
print("\n To get any of the one condition to get true among the two conditions given.")
filtered_or  = df[(df["Salary"] < 28000) | (df["Performance Score"] < 95)]
print(filtered_or)
By using & in two conditions both the condition must be fufilled to get the desired result.(& = and)
By using | in two conditions either of the two conditions must be true to get the desired result.(| = or)**



df["Bonus"] = df["Salary"] * 0.1 # To add a new column in a given dataset.



df.insert(2,"Employee ID",[11,12,13,14,15,16,17,18]) #To add  a new column in a dataset but with desired location.
SYNTAX : df.insert(location where the column is needed to be add , Name of new column , Data of the new column )



df.drop(columns = ["Performance Score"],inplace = True)  #To remove a particular column in a given dataset
By writing inplace is true we will update the original dataset else the system will give us a new dataset itself.


df.drop(columns = ["Performance Score","Age"],inplace = True) #To remove multiple columns from a single dataset.


print(df.isnull()) #Tell us whether the dataframe contains a null value or not.
If the result is True it means it contains a null value else it contains some type of value.\

print(df.isnull().sum()) #Tells us the total number of null values and also the column in which it consists.

df.dropna(inplace = True) #df.dropna is used to remove the empty or null values form the dataset.
If we write df.dropna(axis = 0) , axis 0 means it will remove null value only from the rows and the axis = 1 means it will remove the null values from columns.
inplace = True ,  is written to change or update the original dataset instead of creation of a new dataset.
#To replace the null value with our own new value.

df.fillna(2000,inplace=True)#df.fillna is used to add a new value in the place of null or empty value.
It will replace all null values with the new value , no matter they are name , age , performance score or any other category etc.
SYNTAX : df.fillna(value,inplace = True)





df["Performance Score"] = df["Performance Score"].fillna(df["Performance Score"].mean())
SYNTAX : df["column(whose value is needed to be changed)"] = df["column(whose value is being changed).fillna(df["column name(whose value is being changed)"].new value
(In this case , we are taking mean of the whole column as the mean will not change the original form or answer or overview of the whole dataframe. ))"]





In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat",None,"Shivam"],
    "Age":[21,23,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,None]
}
df = pd.DataFrame(data)
print(df)

df.fillna(2000,inplace=True)#df.fillna is used to add a new value in the place of null or empty value.
#It will replace all null values with the new value , no matter they are name , age , performance score or any other category etc.
#SYNTAX : df.fillna(value,inplace = True)

print(df)


      Name  Age  Salary  Performance Score
0  Krishan   21   30000               99.0
1   Kartik   23   20000               98.0
2  Rakshit   32   12000                9.0
3    Anish   34   23000               98.0
4    Ayush   55   23500               97.0
5    Manan   43   12000               97.0
6   Akshat   45   33333               98.0
7     None   34   23400               90.0
8   Shivam   23   18000                NaN
      Name  Age  Salary  Performance Score
0  Krishan   21   30000               99.0
1   Kartik   23   20000               98.0
2  Rakshit   32   12000                9.0
3    Anish   34   23000               98.0
4    Ayush   55   23500               97.0
5    Manan   43   12000               97.0
6   Akshat   45   33333               98.0
7     2000   34   23400               90.0
8   Shivam   23   18000             2000.0


In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat",None,"Shivam"],
    "Age":[21,23,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,None]
}
df = pd.DataFrame(data)
print(df)

#To replace a particular value only

df["Performance Score"] = df["Performance Score"].fillna(df["Performance Score"].mean())
#SYNTAX : df["column(whose value is needed to be changed)"] = df["column(whose value is being changed).fillna(df["column name(whose value is being changed)"].new value
#(In this case , we are taking mean of the whole column as the mean will not change the original form or answer or overview of the whole dataframe. ))"]
print(df)

      Name  Age  Salary  Performance Score
0  Krishan   21   30000               99.0
1   Kartik   23   20000               98.0
2  Rakshit   32   12000                9.0
3    Anish   34   23000               98.0
4    Ayush   55   23500               97.0
5    Manan   43   12000               97.0
6   Akshat   45   33333               98.0
7     None   34   23400               90.0
8   Shivam   23   18000                NaN
      Name  Age  Salary  Performance Score
0  Krishan   21   30000              99.00
1   Kartik   23   20000              98.00
2  Rakshit   32   12000               9.00
3    Anish   34   23000              98.00
4    Ayush   55   23500              97.00
5    Manan   43   12000              97.00
6   Akshat   45   33333              98.00
7     None   34   23400              90.00
8   Shivam   23   18000              85.75


**Interpolation in Pandas is a method used to fill missing values or null values in a dataframe or Series by estimating the values from nearby data points,often using linear or polynomial or time methods.**

**Pros:**
*Very useful in time series data.(Data which is collected and recorded over time.)
*Very useful in numeric data with trends (Stock market Analysis).
*Avoid dropping rows as it can affect the overall data.

**Cons:**
*Cannot work with categorical data(name,id,performance score etc.)
*It assumes a predictable pattern which might not satisfy the actual value or data.

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shyam","Shivam"],
    "Age":[21,None,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,89]
}
df = pd.DataFrame(data)
print(df)

df.interpolate(method = "linear",axis = 0 , inplace = True)

#SYNTAX : df.interpolate(method which we are gonna insert a new estimated value, axis either 0 or 1 i.e. for rows or columns , inplace true so that changes will occur in original dataframe.)
print(df)

#To change  a desired column
#SYNTAX : df["Salary"].interpolate(method = "linear",axis = 0,inplace = True)

#To change a desired row
#SYNTAX : df.loc[2].interpolate(method="linear",axis = 0 , inplace = True)

#df.interpolate(method = "time",axis = 0 , inplace = True)
#df.interpolate(method = "polynomial",axis = 0 , inplace = True)

      Name   Age  Salary  Performance Score
0  Krishan  21.0   30000                 99
1   Kartik   NaN   20000                 98
2  Rakshit  32.0   12000                  9
3    Anish  34.0   23000                 98
4    Ayush  55.0   23500                 97
5    Manan  43.0   12000                 97
6   Akshat  45.0   33333                 98
7    Shyam  34.0   23400                 90
8   Shivam  23.0   18000                 89
      Name   Age  Salary  Performance Score
0  Krishan  21.0   30000                 99
1   Kartik  26.5   20000                 98
2  Rakshit  32.0   12000                  9
3    Anish  34.0   23000                 98
4    Ayush  55.0   23500                 97
5    Manan  43.0   12000                 97
6   Akshat  45.0   33333                 98
7    Shyam  34.0   23400                 90
8   Shivam  23.0   18000                 89


/tmp/ipython-input-3067965130.py:11: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method = "linear",axis = 0 , inplace = True)


**Sorting Data is the method of sorting data according to  our choice either in alphabatical order , ascending order or descending order**

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shyam","Shivam"],
    "Age":[21,66,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,89]
}
df = pd.DataFrame(data)
print(df)

df.sort_values(by = "Age",ascending = False,inplace = True)
#SYNTAX : df.sort_values(by = "Column which is needed to be sorted",ascending ="True or Flse meaning either to sort in ascending order or descending order.")

#For multiple columns
#SYNTAX : df.sort_values(by = ["column name 1 ","column name 2 "],ascending = [(True, False)],inplace=True)
#Simply for multiple columns write columns names in a list and ascening order too in list according to our preference.
print(df)

      Name  Age  Salary  Performance Score
0  Krishan   21   30000                 99
1   Kartik   66   20000                 98
2  Rakshit   32   12000                  9
3    Anish   34   23000                 98
4    Ayush   55   23500                 97
5    Manan   43   12000                 97
6   Akshat   45   33333                 98
7    Shyam   34   23400                 90
8   Shivam   23   18000                 89
      Name  Age  Salary  Performance Score
1   Kartik   66   20000                 98
4    Ayush   55   23500                 97
6   Akshat   45   33333                 98
5    Manan   43   12000                 97
7    Shyam   34   23400                 90
3    Anish   34   23000                 98
2  Rakshit   32   12000                  9
8   Shivam   23   18000                 89
0  Krishan   21   30000                 99


In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shyam","Shivam"],
    "Age":[21,None,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,89]
}
df = pd.DataFrame(data)
print(df)

df["Salary"].mean() #To calculate mean or average of the desired column.
df["Salary"].sum()  #To calculate sum of the desired column.
df["Salary"].min()  #To calculate minimum or least value of the desired column.
df["Salary"].max()  #To calculate maximum or highest of the desired column.

**Grouping is basically the method of dividing a large dataset into smaller parts for easy working and manipulation or cleaning**

In [ ]:
import pandas as pd
data = {
    "Name":["Krishan","Kartik","Rakshit","Anish","Ayush","Manan","Akshat","Shyam","Shivam"],
    "Age":[21,None,32,34,55,43,45,34,23],
    "Salary":[30000,20000,12000,23000,23500,12000,33333,23400,18000],
    "Performance Score":[99,98,9,98,97,97,98,90,89]
}
df = pd.DataFrame(data)
print(df)
grouped = df.groupby("Age")["Salary"].sum()
#SYNTAX : df.groupby(Column 1 in which the grouping is to be done.)["Column 2  in square brackets means on which column we wanna work "].sum(operation to be performed with column 2 )
#SYNTAX : df.groupby("Column_to_group_by")["Column_to_aggregate"].function(function to be performed.)
print(grouped)


#For multiple columns
#SYNTAX : df.groupbr(["Age","Name"])["Salary"].sum


#Some functions that can be performed in grouping
"""
.sum() for sum
.mean() for mean or average
.count() for counting the number of unique values in the  whole column selected or number of times a particular value is being repeated
.sum() for finding the minimum or least value
.sum() for finding maximum or highest value
.std() for finding the standard deviation value
"""

      Name   Age  Salary  Performance Score
0  Krishan  21.0   30000                 99
1   Kartik   NaN   20000                 98
2  Rakshit  32.0   12000                  9
3    Anish  34.0   23000                 98
4    Ayush  55.0   23500                 97
5    Manan  43.0   12000                 97
6   Akshat  45.0   33333                 98
7    Shyam  34.0   23400                 90
8   Shivam  23.0   18000                 89
Age
21.0    30000
23.0    18000
32.0    12000
34.0    46400
43.0    12000
45.0    33333
55.0    23500
Name: Salary, dtype: int64


**Merging in pandas is the concept of joining two or more rows of  a dataframe on basis of common key column**

In [ ]:
import pandas as pd
df_customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Krishan","Ayush","Rakshit"]
})
print(df_customers)

df_orders = pd.DataFrame({
    "CustomerID":[1,5,6],
    "Order value":[234,456,667]
})
print(df_orders)

#After merging both the dataframes.

df_merged = pd.merge(df_customers,df_orders,on = "CustomerID",how = "inner")
#SYNTAX : pd.merge(column 1,column 2  , on = "column which is common in both the dataframes or on which the merging is to be done",how = "method on whose basis the merging is being done.")
print("On basis of inner join method") #Will merge the columns on whose basis the merging is done and merge the values which are common in both the dataframe
print(df_merged)

#how = outer
#Will join all the rows in both the dataframe and insert NaN values in the empty places.

#how = cross
#Will join all the rows in both the dataframe and basicallyy produce a cartisian product of both the dataframe.



   CustomerID     Name
0           1  Krishan
1           2    Ayush
2           3  Rakshit
   CustomerID  Order value
0           1          234
1           5          456
2           6          667
On basis of inner join method
   CustomerID     Name  Order value
0           1  Krishan          234


**Concatenation means joining multiple DataFrames or Series together along rows or columns (like stacking them).**

In [ ]:
import pandas as pd
df_customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Krishan","Ayush","Rakshit"]
})
print(df_customers)

df_orders = pd.DataFrame({
    "CustomerID":[1,5,6],
    "Order value":[234,456,667]
})
print(df_orders)

df_concate = pd.concat([df_customers,df_orders],axis = 0 , ignore_index = True)
#SYNTAX : pd.concat(["Dataframe 1",["Dataframe 2"],axis = 0 or 1 , ignore_index = True or False])
#First we will select the dataframes to be concated ,Than we will select that either we want them to be concated row wise or column wise
#At last, we will ignore the index(True) to reconsider or do the indexing again after stacking of the dataframes.

print(df_concate)

   CustomerID     Name
0           1  Krishan
1           2    Ayush
2           3  Rakshit
   CustomerID  Order value
0           1          234
1           5          456
2           6          667
   CustomerID     Name  Order value
0           1  Krishan          NaN
1           2    Ayush          NaN
2           3  Rakshit          NaN
3           1      NaN        234.0
4           5      NaN        456.0
5           6      NaN        667.0


In [ ]:
#Homework Question

import pandas as pd
df_customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "Name":["Krishan","Ayush","Rakshit"]
})
print(df_customers)

df_orders = pd.DataFrame({
    "CustomerID":[1,5,6],
    "Order value":[234,456,667]
})
print(df_orders)

df_combine = pd.merge(df_customers,df_orders,on = "CustomerID",how = "inner")
print(df_combine)

df_3_data = { # Renamed the dictionary to avoid confusion
    "Name":["KK","LL","LK"],
    "Age":[12,34,55]
}
df_3 = pd.DataFrame(df_3_data) # Create a DataFrame from the dictionary
print(df_3) # Print df_3 to see its structure

# Now concatenate the DataFrames
df_concate = pd.concat([df_combine, df_3], axis = 0 , ignore_index = True)
print(df_concate)

   CustomerID     Name
0           1  Krishan
1           2    Ayush
2           3  Rakshit
   CustomerID  Order value
0           1          234
1           5          456
2           6          667
   CustomerID     Name  Order value
0           1  Krishan          234
  Name  Age
0   KK   12
1   LL   34
2   LK   55
   CustomerID     Name  Order value   Age
0         1.0  Krishan        234.0   NaN
1         NaN       KK          NaN  12.0
2         NaN       LL          NaN  34.0
3         NaN       LK          NaN  55.0


#Numpy Beginning

In [ ]:
import numpy as np #To import numpy library
temprature = np.array([33,45,63,23,34,43])#To create an array in numpy
average = np.mean(temprature)#To find mean
print(average)
print(temprature)#Array in numpy is written without commas in output

print(np.mean(temprature))

40.166666666666664
[33 45 63 23 34 43]
40.166666666666664


In [ ]:
#Array is used to store data elements of same type.
import numpy as np
arr_1d = np.array([2,3,4,5,6,7])
print(f"One dimensional array is : {arr_1d}")

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(f"Two dimensional array is : {arr_2d}")


In [ ]:
#Creation of array in numpy
import numpy as np
#METHOD : 1 (creating array from numpy lists.)
arr = np.array([1,2,3])
print(arr)

#With default values
#np.zeros((shape))    (3) for 1D array  and (3,3) for 2D array

zeros_array = np.zeros((3,4))
print(zeros_array)#For printing an array of our desired shape with default value as zero


ones_array = np.ones((4,2))
print(ones_array)#For printing an array of our desired shape with default value as one


#For creating an array with our desired shape and a desired value
#array = np.full((shape),value)

desired_array = np.full((4,5),8)#Desired shape is 4 rows and 5 columns whereas the desired value or default value is 8
print(desired_array)



#To create sequence of numbers in numpy
#np.arange(start,stop,step)
#The value from where the array is needed to be start.
#The value at which the array is needed to stop or end.
#Step , the value given - 1(These many values are to be skipped between two consecutive numbers)

sequence_array = np.arange(1,100,2)
print(sequence_array)



#To create an idendity matrix
#np.eye(size)

identity_matrix = np.eye(5)
print(identity_matrix)

[1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
# The error is because the inner lists have different lengths.
# NumPy arrays require all dimensions to have the same size.
array = np.array([[33,44,55,66,77,88,99],
                  [22,3, 0, 0, 0, 0, 0]]) # Added placeholder zeros to match the length of the first list
print(array)

#To know shape of a array.Simply print :
#SYNTAX : name_of_array.shape
print(array.shape)
#It will give output rows,columns.

#To know the number of elements being contained in a array.
#SYNTAX : name_of_array.size
print(array.size)

[[33 44 55 66 77 88 99]
 [22  3  0  0  0  0  0]]
(2, 7)
14


In [ ]:
import numpy as np
arr_1d = np.array(["Krishan","Akshat","Rakshit"])
arr_2d = np.array([[2,3,4],[3,4,5]])
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])

#To know number of dimensions of a array contain or has.
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

#To know the type of datatype a array contain
print(arr_1d.dtype) #U in output means string and number after is the maximum length of the string it contains
print(arr_2d.dtype)#int64 means it contains integer type values and float64 means it contains float or decimal type of values.


1
2
2
<U7
int64


In [ ]:
#To change datatype of the array
import numpy as np
array = np.array([12,34,56,78,99.66]) #To create an array
int_array = array.astype(int)#To convert datatype of the array
#SYNTAX : new array = old array.astype(data type in which the array is gonna be changed)
print(int_array)

print(int_array.dtype)


#Mathematical functions which we can perform on numpy


[12 34 56 78 99]
int64


In [ ]:
import numpy as np

# Create two sample NumPy arrays
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

print("Array 1:", array1)
print("Array 2:", array2)

# Addition
addition_result = array1 + array2
print("\nAddition (array1 + array2):", addition_result)

# Subtraction
subtraction_result = array1 - array2
print("Subtraction (array1 - array2):", subtraction_result)

# Multiplication
multiplication_result = array1 * array2
print("Multiplication (array1 * array2):", multiplication_result)

# Division
division_result = array1 / array2
print("Division (array1 / array2):", division_result)

# Element-wise operations
scalar = 5
scalar_addition = array1 + scalar
print("\nScalar Addition (array1 + 5):", scalar_addition)

scalar_multiplication = array1 * scalar
print("Scalar Multiplication (array1 * 5):", scalar_multiplication)

square_result = array1**2
print("\nSquare of the Array is (array1**2):",square_result)

# Other useful mathematical functions
print("\nMean of array1:", np.mean(array1))
print("Sum of array1:", np.sum(array1))
print("Maximum value in array1:", np.max(array1))
print("Minimum value in array1:", np.min(array1))

# Standard deviation and variance
print("\nStandard deviation of array1:", np.std(array1))
print("Variance of array1:", np.var(array1))

Array 1: [10 20 30 40]
Array 2: [1 2 3 4]

Addition (array1 + array2): [11 22 33 44]
Subtraction (array1 - array2): [ 9 18 27 36]
Multiplication (array1 * array2): [ 10  40  90 160]
Division (array1 / array2): [10. 10. 10. 10.]

Scalar Addition (array1 + 5): [15 25 35 45]
Scalar Multiplication (array1 * 5): [ 50 100 150 200]

Square of the Array is (array1**2): [ 100  400  900 1600]

Mean of array1: 25.0
Sum of array1: 100
Maximum value in array1: 40
Minimum value in array1: 10


**Indexing is the method of picking or working with only one special element in a array**

**Slicing is the method of picking a group or block of elements in a array and than working on them.**

In [ ]:
import numpy as np
arr_1d = np.array([2,3,4,5,67,8,9,90]) #One dimensional array
element = arr_1d[2] #For indexing of 1D array simply just
#SYNTAX: array_name[index number]
print(element)

arr_2d = np.array([[22,33,44,55,66],[1,2,3,4,5]]) #2 Dimensional array
new_element = arr_2d[1, 2] # Accessing the element in the second row (index 1) and third column (index 2)
print(new_element)

4
3


In [ ]:
import numpy as np
arr_1d = np.array([2,3,4,5,67,8,9,90])
slicing = arr_1d[0:6:1]
#Slicing is done basically by selecting the array and than entering the start value , stop value(Will not be included) , step value(-1)(number of values to be skipped)
print(slicing)

#To get a array in reverse
new_slicing = arr_1d[7::-1]
#For negative slicing simply intechange the start and end value .If you wanna include the first elemnt too in a straight array simply leave the space blank.
print(new_slicing)


#Fancy slicing is the method to select multiple elements of different index values at once.
fancy_slicing = arr_1d[[1,4,6]] # For fancy slicing simply pass the required elemnts in a form of list
print(fancy_slicing)


#For giving any condition to be performed in a array
condition = arr_1d[arr_1d>5] # Corrected boolean indexing syntax  ALSO KNOWN AS BOOLEAN MASKING.
print(condition)

[ 2  3  4  5 67  8]
[90  9  8 67  5  4  3  2]
[ 3 67  9]
[67  8  9 90]


In [ ]:
#Reshaping is the method of changing the shape of the array.
#NOTE : 1)Number of elements in the array remains the same,only the shape is changed.
#       2)Reshaping occurs only when the dimensions of the array match.
import numpy as np
arr_1d = np.array([2,3,4,5,67,8,9,90])

shaped_array = arr_1d.reshape(2,4)#Will create 2 rows and 4 columns
print(shaped_array)
#Reshaping an array never gives a new copy it just gives a view of the new shaped array.


#Flattening is the method of converting the multidimensional array in a 1D array.
#Has two types:1)  .ravel()    for getting the view.
#              2)  .flatten()  for getting the copy of new shaped array.

import numpy as np
arr_1d = np.array([[2,3,4,5],[67,8,9,90]])
print(arr_1d.ravel()) #Will give only the view
print(arr_1d.flatten()) #Will give the copy of the new shaped array



[[ 2  3  4  5]
 [67  8  9 90]]
[ 2  3  4  5 67  8  9 90]
[ 2  3  4  5 67  8  9 90]


#Advanced NumPy

In [ ]:
#To insert a value in an array
import numpy as np
arr_1d = np.array([2,3,4,5,67,8,9,90]) #Previous array.
new_array = np.insert(arr_1d,3,566,0)
"""SYNTAX : np.insert(name of array where the value is to be inserted ,
                    location or index value where the value is to be inserted,
                    value which is needed to be inserted,
                    axis either 0 or 1 depending on the value is gonna be inserted in a row or column #Not required for 1 D array.

                     """

print(new_array)



arr_2d = np.array([[2,3,4,5],[67,8,9,90]])
print(arr_2d)
new_2d_array = np.insert(arr_2d,1,[1,2,3,4],0) #Will add on index 1 from row side as axis = 0.
print(new_2d_array)


arr = np.array([[1,2,],[3,4]])
new_array2 = np.insert(arr,1,[5,6],1) #Elemnts are added in in the index value 1 for axis 1 which is column
print(new_array2)

#If we put axis none than the new array created will be flattened meaning all the elemnts will be added in a single row.
arr_d = np.array([[2,3,4,5],[67,8,9,90]])
print(arr_d)
new_arrayd = np.insert(arr_d,1,[5,6],None)
print(new_arrayd)


[  2   3   4 566   5  67   8   9  90]
[[ 2  3  4  5]
 [67  8  9 90]]
[[ 2  3  4  5]
 [ 1  2  3  4]
 [67  8  9 90]]
[[1 5 2]
 [3 6 4]]
[[ 2  3  4  5]
 [67  8  9 90]]
[ 2  5  6  3  4  5 67  8  9 90]


In [2]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)

#We can insert a new element at the end of the array bu using append function.
#A new array will be created without changing the initial array.
#SYNTAX : np.append(name of array , value to be inserted)

new_array = np.append(array,2)
print(new_array)

[1 2 3 4 5 6 7 8 9 0]
[1 2 3 4 5 6 7 8 9 0 2]


**Concating array is a process of joining or merging two arrays in a single array**

In [16]:
import numpy as np
array1 = np.array([1,2,3,4])
array2 = np.array([7,8,9,0])
concated_array = np.concatenate((array1,array2),axis = 0) #Axis 0 will join the arrays in a single row
print("Both the arrays are merged : ",concated_array)


array3 = np.array([[1,2],[3,4]]) # Corrected syntax for 2D array
array4 = np.array([[7,8],[9,0]]) # Corrected syntax for 2D array
concated_new_array = np.concatenate((array3,array4),axis = 1)
print("Both the arrays are merged with axis =0 : ",concated_new_array)


concated_new_array = np.concatenate((array3,array4),axis = 0)
print("Both the arrays are merged with axis =1 : ",concated_new_array)


Both the arrays are merged :  [1 2 3 4 7 8 9 0]
Both the arrays are merged with axis =0 :  [[1 2 7 8]
 [3 4 9 0]]
Both the arrays are merged with axis =1 :  [[1 2]
 [3 4]
 [7 8]
 [9 0]]


In [19]:
#To delete an particular element from an array.
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,0])
new_array = np.delete(array,2,0)
#SYNTAX : np.delete(name_of_array , index from where value is to be deleted,axis either 0 or 1 i.e. either rows or columns.)
print(new_array)

#To stack arrays either horizontally or vertically.
array1 = np.array([1,2,3,4])
array2 = np.array([7,8,9,0])
new_vertically_stacked_array = np.vstack((array1,array2))
print("Vertically stacked array is : ",new_vertically_stacked_array)


new_horizontally_stacked_array = np.hstack((array1,array2))
print("Horizontally stacked array is : ",new_horizontally_stacked_array)

[1 2 4 5 6 7 8 9 0]
Vertically stacked array is :  [[1 2 3 4]
 [7 8 9 0]]
Horizontally stacked array is :  [1 2 3 4 7 8 9 0]


In [23]:
#To split or divide an array in different small arrays
import numpy as np

# Create a 2D array for demonstration of vsplit
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])

print("Original 2D array:")
print(array_2d)

# np.split divides array into desired equal parts.
# If the number of values are less such that it cannot be divided in equal parts , than it will give a ValueError
# SYNTAX : np.split(name_of_array , number of parts to be divided)
new_splitted_array = np.split(array_2d, 2)
print("\nArray splitted in equal parts (using np.split): ")
print(new_splitted_array)


# np.hsplit splits array horizontally
# SYNTAX : np.hsplit(name_of_array , number of parts to be divided)
new_horizontally_splitted_array = np.hsplit(array_2d, 2)
print("\nArray splitted horizontally (using np.hsplit): ")
print(new_horizontally_splitted_array)

# np.vsplit splits array vertically
# SYNTAX : np.vsplit(name_of_array , number of parts to be divided)
new_vertically_splitted_array = np.vsplit(array_2d, 2)
print("\nArray splitted vertically (using np.vsplit): ")
print(new_vertically_splitted_array)

Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array splitted in equal parts (using np.split): 
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]

Array splitted horizontally (using np.hsplit): 
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]

Array splitted vertically (using np.vsplit): 
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


**Broadcasting is the set of rules in numpy which alow performance of mathematical operations on large datasets(arary) without usingloops and increasing effeciency of the program by taking less time.**


In [29]:
import numpy as np
price = np.array([100,200,300,400,500,600,700,800,900])
discount = 12
final_prices = price - (price *discount/100)
print(final_prices)

product = price * 4 #Used to multiply a single elemt with whole of an array without using loops.
print(product)

matrix = np.array([[1,2,3],[4,5,6]]) #Creation of an 2D array
vector = np.array([100,200,300]) #Creation of a single (1D array)
result = matrix + vector #Used to add two arrays despite them of being of different dimensions
print(result)


array1 = np.array([[1,2,3,4],[5,6,7,8]]) #Shape (2,4)
array2 = np.array([100,200])#Shape(1)

#Mathematical operations can't be performed as they are of opposite shapes.
#To perform mathematical operations we have to reshape the array into same shape arrays

new_shaped_array = np.reshape(array2,(2,1)) # Reshaped array2 to (2,1) to demonstrate broadcasting
print(new_shaped_array)

# Now, perform the mathematical operation with broadcasting
broadcasted_result = array1 + new_shaped_array
print("\nResult after broadcasting:")
print(broadcasted_result)

[ 88. 176. 264. 352. 440. 528. 616. 704. 792.]
[ 400  800 1200 1600 2000 2400 2800 3200 3600]
[[101 202 303]
 [104 205 306]]
[[100]
 [200]]

Result after broadcasting:
[[101 102 103 104]
 [205 206 207 208]]


**Vectorization in array is the process of performing mathematical operations on a whole array at once.**

**Vectorization is compatible for same shape arrays**


In [33]:
import numpy as np
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
print("Addition : ",array1 + array2)
print("Multiplication : ",array1*array2)

Addition :  [ 7  9 11 13 15]
Multiplication :  [ 6 14 24 36 50]


In [42]:
#Handling missing values in a datset.
#Three types of built-in-function :
#1) np.isnan()   To detect missing values
#2) np.nan_to_num()  Used to change or replace missing values with a numerical value
#3) np.isinf()  Used to detect infinite values

import numpy as np
array = np.array([1,2,np.nan,4,np.nan,6,7,8]) #Array with some missing values. np.nan is used to show a missing or null value.

print(np.isnan(array)) #Used to find if there is any missing value in an array
#SYNTAX : np.isnan(name_of_array)


#Now to clean the array we use function np.nan_to_num which replaces the nan values with a new value
cleaned_array = np.nan_to_num(array,nan = 123)
#SYNTAX : np.nan_to_num(name_of_array, nan = value to be placed instead of nan values[default value is 0])
print(cleaned_array)


#Now to check if an array contains an positive or negative infinite values
array1 = np.array([1,2,3,4,np.inf,6,7,8,-np.inf])
print(np.isinf(array1)) #Used to check if there is any infinite value or not

cleaned_inf_array = np.nan_to_num(array1,posinf = 12,neginf=1000)
#In inf case we use posinf for positive infinite and neginf for negative infinite values.#Used for replacing them with new values
print(cleaned_inf_array)


#To

[False False  True False  True False False False]
[  1.   2. 123.   4. 123.   6.   7.   8.]
[False False False False  True False False False  True]
[   1.    2.    3.    4.   12.    6.    7.    8. 1000.]


In [43]:
#Handling missing values in a datset.
#Three types of built-in-function :
#1) np.isnan()   To detect missing values
#2) np.nan_to_num()  Used to change or replace missing values with a numerical value
#3) np.isinf()  Used to detect infinite values

import numpy as np
array = np.array([1,2,np.nan,4,np.nan,6,7,8]) #Array with some missing values. np.nan is used to show a missing or null value.

print("Original array:", array)
print("Is NaN array:", np.isnan(array)) #Used to find if there is any missing value in an array
#SYNTAX : np.isnan(name_of_array)


#Now to clean the array we use function np.nan_to_num which replaces the nan values with a new value
cleaned_array = np.nan_to_num(array,nan = 123)
#SYNTAX : np.nan_to_num(name_of_array, nan = value to be placed instead of nan values[default value is 0])
print("\nArray after np.nan_to_num (replacing all NaNs with 123):", cleaned_array)


#Now to check if an array contains an positive or negative infinite values
array1 = np.array([1,2,3,4,np.inf,6,7,8,-np.inf])
print("\nOriginal array with infinite values:", array1)
print("Is infinite array:", np.isinf(array1)) #Used to check if there is any infinite value or not

cleaned_inf_array = np.nan_to_num(array1,posinf = 12,neginf=1000)
#In inf case we use posinf for positive infinite and neginf for negative infinite values.#Used for replacing them with new values
print("\nArray after np.nan_to_num (replacing infinities):", cleaned_inf_array)


# To change the value of a desired NaN value
# We can use boolean indexing to find the indices where the value is NaN and then assign a new value
array_with_nan = np.array([1, 2, np.nan, 4, np.nan, 6, 7, 8])
print("\nArray with specific NaNs to change:", array_with_nan)

# Find the indices where the array is NaN
nan_indices = np.isnan(array_with_nan)

# Replace the NaN values with a desired value (e.g., 999)
array_with_nan[nan_indices] = 999
print("Array after changing specific NaNs:", array_with_nan)

# You can also replace a specific NaN by its index if you know it
array_with_nan_indexed = np.array([1, 2, np.nan, 4, np.nan, 6, 7, 8])
print("\nArray with specific NaNs to change by index:", array_with_nan_indexed)
# Let's say we want to change the NaN at index 2
array_with_nan_indexed[2] = 555
print("Array after changing NaN at index 2:", array_with_nan_indexed)

Original array: [ 1.  2. nan  4. nan  6.  7.  8.]
Is NaN array: [False False  True False  True False False False]

Array after np.nan_to_num (replacing all NaNs with 123): [  1.   2. 123.   4. 123.   6.   7.   8.]

Original array with infinite values: [  1.   2.   3.   4.  inf   6.   7.   8. -inf]
Is infinite array: [False False False False  True False False False  True]

Array after np.nan_to_num (replacing infinities): [   1.    2.    3.    4.   12.    6.    7.    8. 1000.]

Array with specific NaNs to change: [ 1.  2. nan  4. nan  6.  7.  8.]
Array after changing specific NaNs: [  1.   2. 999.   4. 999.   6.   7.   8.]

Array with specific NaNs to change by index: [ 1.  2. nan  4. nan  6.  7.  8.]
Array after changing NaN at index 2: [  1.   2. 555.   4.  nan   6.   7.   8.]
